use_frameworks!

platform :ios, '13.0'

target 'WXLibSwift_Example' do
#  pod 'WXLibSwift', :path => '../'

#  target 'WXLibSwift_Tests' do
#    inherit! :search_paths
#
#    
#  end
end

target 'ttt' do
  pod 'WXLibSwift/Pay', :path => '../'
end
